# Generated by Django 5.0.7 on 2024-07-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineLearningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(verbose_name='точность предсказания')),
                ('dataset', models.FileField(upload_to='datasets', verbose_name='набор данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время')),
            ],
        ),
    ]
