# Generated by Django 5.0.7 on 2024-07-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineLearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningresult',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='модель была запущена'),
        ),
        migrations.AlterField(
            model_name='machinelearningresult',
            name='accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='точность предсказания'),
        ),
        migrations.AlterField(
            model_name='machinelearningresult',
            name='dataset',
            field=models.FileField(null=True, upload_to='datasets', verbose_name='набор данных'),
        ),
    ]
