# Generated by Django 5.0.7 on 2024-07-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineLearning', '0002_machinelearningresult_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningresult',
            name='report',
            field=models.TextField(blank=True, null=True, verbose_name='отчет'),
        ),
    ]
