# Generated by Django 5.0.7 on 2024-07-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineLearning', '0003_machinelearningresult_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinelearningresult',
            options={'verbose_name': 'результат работы модели', 'verbose_name_plural': 'результаты/исходники работы модели'},
        ),
        migrations.AlterField(
            model_name='machinelearningresult',
            name='report',
            field=models.TextField(blank=True, help_text='\n        <i>Этот отчет представляет собой результат работы модели классификации,\n        в данном случае — случайного леса (RandomForestClassifier).</i><br><br>\n    \n        Основные метрики<br><br>\n        1. <b>precision</b> (точность):<br><br>\n           - Это доля правильно предсказанных положительных событий из всех событий, предсказанных как положительные.<br>\n           - Высокая точность означает, что ложных срабатываний мало.\n<br><br>\n        \n        2. <b>recall</b> (полнота, или чувствительность):<br><br>\n           - Это доля правильно предсказанных положительных событий из всех реальных положительных событий.<br>\n           - Высокая полнота означает, что модель выявила большинство положительных событий.<br><br>\n        \n        3. <b>f1-score</b>:<br><br>\n           - Среднее гармоническое между точностью и полнотой. F1-метрика балансирует соотношение между ними.<br>\n           - Высокое значение f1-score означает, что и точность, и полнота высоки.<br><br>\n        4. <b>support</b>:<br><br>\n           - Это количество истинных примеров данного класса в выборке.\n    ', null=True, verbose_name='отчет'),
        ),
    ]
